<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MarlothStrategy.Console.Client\MarlothStrategy.Console.Client.csproj" />
    <ProjectReference Include="..\..\src\MarlothStrategy.Simulation\MarlothStrategy.Simulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\src\MarlothStrategy.Simulation\config\**\*.json"
             Link="config\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
