<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MarlothStrategy.Simulation</RootNamespace>
    <AssemblyName>MarlothStrategy.Simulation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="config\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
