<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MarlothStrategy.Console.Client</RootNamespace>
    <AssemblyName>MarlothStrategy.Console.Client</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarlothStrategy.Simulation\MarlothStrategy.Simulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Msagl" Version="1.1.6" />
    <PackageReference Include="Microsoft.Msagl.Drawing" Version="1.1.6" />
  </ItemGroup>

</Project>
