<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MarlothStrategy.Console.App</RootNamespace>
    <AssemblyName>MarlothStrategy.Console.App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarlothStrategy.Console.Client\MarlothStrategy.Console.Client.csproj" />
    <ProjectReference Include="..\MarlothStrategy.Simulation\MarlothStrategy.Simulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\MarlothStrategy.Simulation\config\**\*.json" Link="config\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
  </ItemGroup>

</Project>
